const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const NexusAuditRecord = sequelize.define('NexusAuditRecord', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  site_name: { type: DataTypes.STRING(255), allowNull: false },
  company: { type: DataTypes.STRING(255), allowNull: false },
  address_line1: { type: DataTypes.STRING(255) },
  address_line2: { type: DataTypes.STRING(255) },
  city: { type: DataTypes.STRING(100) },
  state_province: { type: DataTypes.STRING(100) },
  postal_code: { type: DataTypes.STRING(20) },
  country_code: { type: DataTypes.CHAR(2) },
  audit_date_start: { type: DataTypes.DATEONLY },
  audit_date_end: { type: DataTypes.DATEONLY },
  auditor_name: { type: DataTypes.STRING(255) },
  auditor_company: { type: DataTypes.STRING(255) },
  auditor_email: { type: DataTypes.STRING(255) },
  auditor_phone: { type: DataTypes.STRING(50) },
  site_code: { type: DataTypes.STRING(50) },
  address: { type: DataTypes.STRING(255) },
  country: { type: DataTypes.STRING(100) },
  audit_type: { type: DataTypes.ENUM('on-site', 'remote') },
  audit_scope: { type: DataTypes.ENUM('initial', 'renewal') },
  iso_9001_certified: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  grade: { type: DataTypes.CHAR(1), validate: { isIn: [['A', 'B', 'C', 'D']] } },
  status: {
    type: DataTypes.STRING(20),
    allowNull: false,
    defaultValue: 'draft',
    validate: { isIn: [['draft', 'in-progress', 'submitted', 'closed']] },
  },
  cqmap_version: { type: DataTypes.STRING(20), defaultValue: 'V3.A' },
  next_audit_date: { type: DataTypes.DATEONLY },
  report_date: { type: DataTypes.DATEONLY },
  notes: { type: DataTypes.TEXT },

  // ── cqmAP V3.A Coversheet additions ──
  primary_contact_name: { type: DataTypes.STRING(255) },
  primary_contact_email: { type: DataTypes.STRING(255) },
  primary_contact_phone: { type: DataTypes.STRING(50) },
  audit_contact_name: { type: DataTypes.STRING(255) },
  audit_contact_email: { type: DataTypes.STRING(255) },
  audit_contact_phone: { type: DataTypes.STRING(50) },
  customer_id: { type: DataTypes.STRING(50) },
  cvcs_reference: { type: DataTypes.STRING(100) },
  staff_total: { type: DataTypes.INTEGER },
  staff_in_production: { type: DataTypes.INTEGER },
  previous_audit_type: { type: DataTypes.STRING(50), validate: { isIn: [['on-site', 'remote']] } },
  previous_audit_rank: { type: DataTypes.CHAR(1), validate: { isIn: [['A', 'B', 'C', 'D']] } },
  strengths: { type: DataTypes.TEXT },
  weaknesses: { type: DataTypes.TEXT },
  improvements: { type: DataTypes.TEXT },
  regressions: { type: DataTypes.TEXT },
  next_audit_remote_allowed: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  production_volumes: { type: DataTypes.JSONB, allowNull: false, defaultValue: {} },
  created_by: { type: DataTypes.INTEGER },
}, {
  tableName: 'nexus_audit_records',
  underscored: true,
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
});

module.exports = NexusAuditRecord;
